server:
  port: 8765

spring:
  application:
    name: admin-service
  boot:
    admin:
      discovery:
        ignored-services: gateway-service

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://alejandromarin.ddns.net:8761/eureka
  instance:
    hostname: alejandromarin.ddns.net
